name: Deploy Docs to Github Pages

# This workflow builds and deploys the documentation to GitHub Pages
# It uses the gh-pages branch for deployment and requires contents:write permission
on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: docs/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install
        working-directory: ./docs

      - name: Build with VitePress
        run: pnpm build
        working-directory: ./docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/.vitepress/dist
          cname: ${{ github.repository_owner == 'suculent' && 'rusocks.io' || '' }}
          force_orphan: true