name: Deploy Docs to Github Pages

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: docs/pnpm-lock.yaml

      - name: Setup Pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install
        working-directory: ./docs

      - name: Build with VitePress
        run: pnpm build
        working-directory: ./docs

      - name: Deploy to GitHub Pages
        if: ${{ secrets.PAGES_DEPLOY_KEY != '' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.PAGES_DEPLOY_KEY }}
          external_repository: suculent/rusocks.github.io
          publish_branch: main
          publish_dir: docs/.vitepress/dist